List constraint
Ulm-IQO/qudi-core pull request #104
Opened 2024-07-30 18:36 UTC by TobiasSpohn

## Description
Added `DiscreteScalarConstraint` that expands the capability of checking whether a value is in bounds to also check whether it is in a discrete value set. Also added some descriptive docstrings from the discussion in the qudi meeting.

## Motivation and Context
Sometimes a `ScalarConstraint` that only checks whether a value is in bounds is not sufficient. Some devices can only set values from a certain set of discrete values. `DiscreteScalarConstraint` offers the possibility to check whether a value is not only in bounds but also matches the discrete value set of the constraint. It accepts integers and floating point values. For the latter a precision can be specified up until which the equality of the value and the underlying discrete value set is checked against.

## How Has This Been Tested?
Created an instance of the class with discrete value set (int and float) and checked for different values (int and float) if the checkers behave as expected.

## Types of changes
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change (Causes existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added/updated the config example for any module docstrings as necessary.
- [x] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [x] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

2024-09-03 16:24 UTC, Neverhorst requested changes
Thank you for adding the numpy-style docstrings.

Is there a reason why you exchanged all the string single quotes with double quotes? Also the formatting of existing method signatures seems unnecessary. Both were perfectly fine. Please do not use automatted code refactoring on existing qudi modules unless they have been messy before since this clutters the git history.

2024-09-05 17:45 UTC, TobiasSpohn commented
I reverted the formatted code back.

2024-10-18 12:45 UTC, TobiasSpohn commented
Following our discussion I changed the `__init__` of the new `DiscreteScalarConstraint` to only accept a `value_set` and no longer accept `bounds` and `increment`. `Increment` will not be set and `bounds` will just be calculated from min and max values of `value_set`.

2024-10-19 10:27 UTC, Neverhorst requested changes
Hi @TobiasSpohn ,

I refined some docstrings and added deprecation warnings to compatibility properties of `ScalarConstraint` soon to be removed (at least the setters).

Also, I renamed `value_set` init argument and property to `allowed_values` to make it more descriptive (do not use type descriptors in attribute/variable names). It can handle any iterable type now and `__init__` will dump duplicates and turn it into a sorted, immutable tuple.

The `clip` method has also been implemented by me and the base class description has been adjusted. The purpose of this method is to clip the value to the nearest allowed value. This can apply to both `ScalarConstraint` _and_ `DiscreteScalarConstraint`.

I tested it some and for me it seems to work fine now. 
Could you test it again please with your use-case and then it is ready to merge.

2024-10-21 20:19 UTC, TobiasSpohn commented
Hi @Neverhorst,

I tested the changes and they work great with the QDyne module. From my side we can merge it.

2024-10-21 21:02 UTC, Neverhorst approved these changes

2024-10-21 21:04 UTC, merged