Converting the old docstrings to numpydoc style and hiding the license from rendering in every file
Ulm-IQO/qudi-core pull request #115
Opened 2024-09-28 15:03 UTC by George-Elhamy

## Description
These changes are mainly on converting the already found docstrings in src into numpydoc style which is more readable and better looking when rendered in sphinx and this has been done in two different commits. Along with that, the license have also been hidden from rendering (it still shows in the code in every rst file in the src & it also still shows in the documentation but only in the license section) and this has been done on two commits. There is also two python scripts included in the first commit that claculate the documentation coverage in the whole project so that we can track the coverage as we go on with adding the missing documentation for methods and classes. 

## Motivation and Context

## How Has This Been Tested?

## Screenshots (only if appropriate, delete if not):

## Types of changes

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change (Causes existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have documented my changes in `/docs/changelog.md`.
- [ ] My change requires additional/updated documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added/updated the config example for any module docstrings as necessary.
- [x] I have checked that the change does not contain obvious errors
(syntax, indentation, mutable default values, etc.).
- [ ] I have tested my changes using 'Load all modules' on the default dummy configuration.
- [ ] All changed Jupyter notebooks have been stripped of their output cells.

2024-09-30 10:02 UTC, timoML commented
To see the built version:
https://qudi-core-testing.readthedocs.io/en/george/index.html

2024-10-04 13:04 UTC, Neverhorst requested changes
- In my understanding the leading `..` is not necessary for each line of docstrings and should be removed (except for the very few places where it might be needed).
- Some leftovers from merging conflicts are still in the code
- Indentation is broken for a lot of method docstrings
- Keep single quote string literals to not clutter the commit log and keep it uniform. I stopped marking them at some point because roughly half of the changes in this PR stem from this issue.
- New files need copyright and license disclaimers
- Merge `pyproject.toml` with current `main`. Seems like it is rewriting everything
- Remove `src/qudi/util/uic.py.patch` from this PR
- Remove `src/qudi/util/units.py.patch` from this PR

2024-10-05 18:35 UTC, prithviulm commented
Sorry for again making numerous changes and for the force push. This was a mess unfortunately. Hopefully the PR is easier to review now. I've tried to remove all the double quote changes and other formatting changes and other mistakes in the docstrings and licenses etc.

2024-10-07 07:43 UTC, timoML commented on src/qudi/core/parentpoller.py
> +            raise TypeError("argument quit_function must be a callable.")
unecessary change of string literal.

2024-10-07 07:46 UTC, timoML commented on src/qudi/core/statusvariable.py
> +        assert callable(func), "StatusVar constructor/representer must be callable"
Unecessary change of string literal.

2024-10-07 07:50 UTC, timoML commented on src/qudi/util/datastorage.py
> +    PNG = ".png"
Unecessary change of string literal.

2024-10-07 07:51 UTC, timoML commented on src/qudi/util/datastorage.py
> +    pass
Intendation error will brake function.

2024-10-07 07:53 UTC, timoML commented on src/qudi/util/linear_transform.py
> +        raise ValueError("The support vectors should have a length of 3.")
Unecessary change of string literal.

2024-10-07 07:55 UTC, timoML commented on src/qudi/util/mutex.py
> +    def acquire(
function signature does not follow project standards

2024-10-07 07:55 UTC, timoML commented on src/qudi/util/mutex.py
> +        def acquire(
function signature does not follow project standards

2024-10-07 07:57 UTC, timoML commented on src/qudi/util/uic.py
> +    file_path :
docstring seems broken

2024-10-07 07:58 UTC, timoML commented on src/qudi/util/uic.py
> +    file_path :
docstring seems broken

2024-10-07 08:00 UTC, timoML commented on src/qudi/util/uic.py
> +        str|NoneType: Converted file content of the .ui file, None if conversion is not needed
type definition seems broken

2024-10-07 08:05 UTC, timoML commented
- I think Sphinx files (Makefile, conf.py) should go into a seperate folder docs/sphinx
- Did we want to keep string literals as they were or change to consistent use?

2024-10-21 10:19 UTC, timoML commented
Runs on dummy with "load all modules". So indentation in (non-docstring) code seems fine.

2024-11-04 11:52 UTC, Neverhorst commented
Is the double-dot `..` in the license/copyright disclaimer needed? Seems weird to introduce this in all files since it is not required for a simple text body as far as I understand.

2024-11-04 12:27 UTC, timoML commented
It's indicating to sphinx to not render the license for the documentation of every class.
Is there another way for achieving the same?

2024-11-04 13:13 UTC, Neverhorst commented
> It's indicating to sphinx to not render the license for the documentation of every class. Is there another way for achieving the same?

Not from the top of my head but this documentation on [docstring preprocessing](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#docstring-preprocessing) seems promising.

2024-11-04 13:14 UTC, prithviulm commented
It assumes that text at the top of the file is the module docstring and so the license also gets rendered along with the module docstring (if any). There might be some kind of workaround using regex to intercept the text and remove the license after Sphinx reads the text but before it starts parsing.

2024-11-18 13:58 UTC, prithviulm commented
Ok, I think this is ready to merge now. Fixed a few more docstrings that were not converted. Reverted the license back to remove the leading `..`. As discussed, a style guide is necessary for things like when and where to use newlines in docstrings as Ruff will not handle these. I will add a brief description of it to the Ruff config.

2024-11-18 14:41 UTC, timoML approved these changes
Looks good now, thanks for the effort.

2024-11-18 15:21 UTC, prithviulm commented
Check that it still runs on dummy with "load all modules".

2024-11-25 10:50 UTC, prithviulm commented
@Neverhorst We've addressed the remaining changes but can't merge till you approve.

2024-11-25 11:05 UTC, Neverhorst approved these changes
Thank you for your effort @prithviulm . Looks very good now.
Merging the testing and documentation overhaul "one-thing-at-a-time" makes this way more manageable.

2024-11-25 11:08 UTC, merged